{
    "name": "Fabrication Management",
    "summary": """Industrial Fabrication management module""",
    "author": "bizzappdev",
    "version": "15.0.0.0.1",
    "license": "LGPL-3",
    "depends": [
        "stock",
        "sale_management",
        "sale_mrp",
        "mrp",
        "purchase",
        "project",
        "contacts",
    ],
    "data": [
        "data/fabrication_data.xml",
        "data/maintenance_cycle_template.xml",
        "data/ir_cron_data.xml",
        "views/product_template_view.xml",
        "views/sale_order_view.xml",
        "views/sale_order_line_view.xml",
        "views/mrp_production_view.xml",
        "views/project_task_view.xml",
        "views/purchase_order_view.xml",
        "views/account_move_view.xml",
        "views/menu_fabrication_management.xml",
    ],
    "demo": ["data/fabrication_demo.xml"],
    "application": True,
    "installable": True,
}
