{
    "name": "Business Flows",
    "summary": "examples of certain sale to other functional flows",
    "author": "BizzAppDev",
    "website": "https://github.com/OCA/contract",
    "version": "15.0.0.0.1",
    "license": "LGPL-3",
    "depends": [
        "sale_management",
        "mrp",
        "project",
        "sale_project",
        "purchase",
    ],
    "data": [
        "views/sale_order_view.xml",
        "views/account_move_view.xml",
        "views/mrp_production_view.xml",
        "views/project_project_view.xml",
        "views/project_task_view.xml",
        "views/purchase_order_view.xml",
        "views/stock_picking_view.xml",
    ],
    "installable": True,
    "application": True,
}
