# hrs worked on: 211.5
{
    "name": "School Management",
    "summary": "management system, with options for students, teachers,refernce",
    "version": "15.0.0.0.1",
    "author": "Manan[MAD]",
    "license": "LGPL-3",
    "depends": ["mail", "base"],
    "data": [
        "security/school_student_security.xml",
        "security/ir.model.access.csv",
        "data/school_sequence_data.xml",
        "data/default_value_data.xml",
        "data/subject_data.xml",
        "data/teacher_data.xml",
        "wizard/teacher_leave_application_wizard_view.xml",
        "views/school_teacher_view.xml",
        "views/former_teachers_view.xml",
        "views/school_subject_view.xml",
        "views/school_reference_view.xml",
        "views/school_student_view.xml",
        "views/student_fees_view.xml",
        "views/teacher_leave_view.xml",
        "views/school_management_menu.xml",
    ],
    "application": True,
    "installable": True,
}
